version: '3'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/codeigniter:3
    ports:
      - '8000:8000'
    volumes:
      - './:/app'
    depends_on:
      - mariadb